import sys
import os
from datetime import datetime, timedelta
from dns.e164 import query
from fastapi import FastAPI
from uuid import uuid4

from sqlalchemy import false
from sqlmodel import Session, select,SQLModel

#coś importy szwankowały czasem w api czasem wąż się buntował
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from app.tools.validationtools import TaskTools
from app.tools.validationtools import PomodoroTools
from app.db.database import engine, SessionDep
from app.db.models import Task, PomodoroSession
from app.tools.validationtools import TaskTools, PomodoroTools
app = FastAPI()

tasks_list = []
pomodoro_list = []

@app.on_event("startup")
def on_startup():

    SQLModel.metadata.create_all(engine)

    with Session(engine) as session:
        tasks = session.exec(select(Task)).all()
        tasks_list.extend(tasks)

        pomodoro_sessions = session.exec(select(PomodoroSession)).all()
        pomodoro_list.extend(pomodoro_sessions)
@app.get("/")
async def read_root():
    #w swaggerze sie nie pokaze to co ma byc :) trzeba w przegldarce"
    #http://127.0.0.1:8000#
    return "ddddddddddddddddxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxoccllllllllooddxxxxxxxxxxxkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000000OOOOOOkkkkkkkkkkkOOOkkxxxxdddddddddddddddddddddddddddddooooooooddddddddxddxdddxxxxxxxxddddddddooddooooool ddddddddddddddxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxdlloodooooooodddxxxxxxxxxxkkkkOOOOOOOOO00OO00OOOOOOOOOOOOOOOOOOOOOO0000000OOOOOOOOkkkkkkkkkkkOkkxxkkxxddddddddddddddddddddddddddddddddoddddddddddddddddddxxxxxxxxxddddddddddddooool dddddddddddddxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxollodddxxdoloodxxxxxxxxxxxxkkkkOOOOOOO000000000000000000000000000000000000000000OOOOOOOkkkkkkkkkkkxkkkxxxddddddddddddddddddddddddddddddddddddddddddxddxxxxxxxxxxxxxxxxxxxxxdddddooll dddddddddddddxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxdocccloddddoooodxxxxxxxxxxxkkkkkkOOOOOOO0000KKKKKKK0000000000000000000KKKKKKKKK000000000OOOOOkkkkkkkkxkkkkkxxxdddxdddddddddddddddddddddddddddddddddddxxxxxxxxxddxxxxxxxxxxxxxdddddooll ddddddddddddddxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxdoc:ccloooooooodxxxxxxxxxxxxkkkkkkkOOOOO000KKKKKKKKKKKK0000000000000000KKKKKKKKKK00000000000OOOkkkkOOkxxkOOkkxxxdddxxxxxdddddddddddddddddddddddddddxxxxxxxxxdxxxdddxxxxxxxxxxxxxddddooo dddddddddddddxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxoc::cllloollooddxxxxxxxxxxxkkkkkkkkOOOOO000KKKKXXXXKKKKKKK0000000000000KKKKKKKKKKKKKKKKKKK000OOOkkkkOOkkxkOOkxxxxdddxxxxxddxddddddddddddddddddddddddxxxxxxxddddxxdddddddxxxxxxxxxddoodd ddddddddddddxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxdl::ccllllllooddxxxxxxxxxxxkkkkkkkkkkOOOO000KKKKXXXXKKKKKKKK0000000000000KKKKKKKKKKKKKKKXXKKK00OOOkkkkOOkxkOOOkxxdxxxddxxddddddddddddxddddddddddddddxxxxxxxxddddxxxxxxxxxxxxddddxxddoodd ddddddddddddxxxxxxxxxxxxxxxkkxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxoccclooolooooddxxxkxxxxxxxxxkkkkkkkkkkOOOO000KKKXXXKKKKKKKK0000000000000KKKKKKKKKKKKKKXXXXXKKK00OOkkkkOOkkkkOOkxxxxxxxxxxdddxxxddddddddddddddddddddxxxxxxxxxddddxxxxxxxxxxxdxxdddddddddo ddddddddddddxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxdcclodollodoooddxxxxxxxxxxxxxkkkkkkkkkkkOOOOO00KKXXXKKKKKKK00000000000000KKKKKKKKKKKKKKXXXXXXKK00OOOkkkkOOkkkOOOkxxxxxxxxxxddxxxxddddddddddddddddddxxdddxxxxddddddxxxxxxxxxddddxxxddddooo ddddddddddddxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxocldddoloooooddxxxxxxxxxxxxxxxxkkkkkkkkkkkOOO00KKKKKKKKK000000000000000000000000KKKKKKKXXXXXXKK00OOOOOOOOOkkkOOOkxxxxxxxxxxxxxxxxxdddddddddddddxxxxdxxxxxxxxxxxxxxxxxxxxxxddddddddddddool dddddddddddddxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxoloxdoolooooddddxxxxxxxxxxxxxxxkkkkkkkkkkkkOO000KKKKKKK0000000OOOOOOO000000000000000KKKKXXXXKKK00OOOOOOOOOkkkOOOkxxxxxxxxxxxxxxxxxddddddddddddxxxxxdddxxxxxxxxxxxxxxxxxxxxdddddddddxddool dddddddddddddxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxdoodolllooooddddxxxxxxxxxxxxxxxxxxkkkkkkkkkkO00000K0000000000000OOOOOOOOOO0000000000000KKKKKKK000OOOOOOkkkkxxkOkkxxxxxxxxxxdddxxxxxxddddddddxxxxxxxdddddxxxxxdxxxxxxxxxxxxdddddddddddoool dddddddddddxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxdoloolllooodddddxxxxxxxxxxxxxxxxxxxxxxkkkkkkOOO00000000OOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000000000OOOOkOkkkkkkxkOOOkxxxxxxxxxxdxxxxxxxxddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddddddddoooo ddddddddxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxolllllloodddddddxxxxddxxxxxxxxxxxxxxxkkkkkkkOOO0000KK00000OOOOOOOOOOOOOOOOOOOOOOO0000000000000OOOkkkkkkkkkkxkO0Okxxxxxxxdxxxxxxxxxxddddddddddddxxxxxxxxxxxddxxxxxxddddddddxxddddoodddoooo ddddddddxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxollllllodddddddddxxxddxxxxxxxxxxxxxxkkkkkkkOOO0000KKKK00000000OOOOOOOOOOOOOOOOOO0000000000OOOOOOkkkkkkkkkkkxxkOOxxxxxxddddxxxxxxxxddddddddddddddxddddddddddddddddddddddddddddddoooooooooo ddddddddxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxolllllloddxdddddxxxxxddxxxxxxxxxxxxxxxxkkkkOOO000KKKK0000000000O0OOOOOOOOOOOOOOOOOOOOO0000OOOOkkkkkkkkkkkxxxxkkkxxxxxxxxxxxxxxxddddddddddddddddddddddddddddddddddddddddddddddddoooooooooo dddddddxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOkxdooollooddxddddxxxxxxxxxxxxxxxxxxxxxxxkkkkOOOO00KKKK00000000000000O000000000000000000000OOOOOOkkkkkkkkkkxxxddxkxxxxxxxxxxxxxxdddddddddddddddddddddddddddddddddddddddddddddddddddooooooooo dddddddxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxddxxxxkkkxdddddddddddddxxxxxxxxxxxxxdddddxxxxxxkkkkOOO00KKKKKK000000000000000OOOOOO000000000000000OOOkkkkxxkkkkxxxxdddxxxxxxxddxdddxddddddddddddddddddddddddddddddddddddddddddddddddddddooooooooo ddddddxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxdxkkkkxdxxxxxxxxdddddxddxxxxxxxxxxxxddddddxxxxxxkkkOOO00KKKKKKKK00000000000000000000000000000000000OOkkkkkxxxkkxxxxxdddxxxxxxxxddxdddddddddddddddddddddddddddddddddddddddddddddddddooddddooooooooo dddddxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxdxOOkkxxxxxxxxxkxxxdxxxxxxxxxxxxxxxdddddddxxxxxkkkkOOO00KKK0000000000000000000000000000000000K00000OOkkkkxxxxxxxxxxddddxxxxxxxxxxxxdddddddddddddddddddddddddddddddddddddddddddddddddddddddoooooooo xddddxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxkOOOkkOkxxxdddxxxxxxxddxxxxxxxxxxdddddddddxxxkkkkkOOO00000000000000000KKK0000000000000000000000000OOkkkkkkxxxxxxxdddddxxxxxxxxxxxxddddddddddddddddddddddddddddddddddddddddddddddddddddddooooooooo xxxddxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxdxOOOOOOOkxxxxdooddddddddxxxxxxxxxxdddxxdddxxxxxxxxxxxkkOOO000000OOOOO000000000000000000000000000OOOOOOOkkkxxxxxxxddddddxxxxxxxxxxxxxddddddddddddddddddddddddddddddddddddddddddddoddddddooooooooooo xxxxxxxxxxxxxxxxxxxxxxxxxxkkxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxkOOOkxddddxkxdooooodddddxxxxxxxxxxddxxdxxxxddddddolllloodxkkOOOOOOOOOOO000000OOOOOOOOO000000OOOOOOOOOOOkkxxxxxxdddddddxxxxxxxxxxxxxxxxxdddddddddddddddddddddddddddddddddddddddoooooddoooooooooooo xxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxkkOOkxollodxxxxdooooodddxxxxxxxxxxxxxxxxdddolllllllcccc:::clodxkkkkkkkkOOOOOOOOOOOOkkkkOOOOOkkkkOOOOOOOOOkkxxxxdddddddddxxxxxxxxxxxxxxxxxddddddddddxxxdddddddddddddddddddddddddoooooodoooooooooooo xxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxkkOOkxddxkkxdxxddoooodddxxxxxxxxkkxxxxxxddolllloooooollcc::::ccoddxxxxxkkkkkkkkkkkkkkxxkkkkkkkkOOOO0000OOkkxxxddddddddddxxxxxxxxxxxxxxxxxxdddddddddddddddddddddddddddddddddddddooooooooooooooooooo xxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxkkkxdxkkOOOxxxddoooddddxxxxxxxxxkkkkkkxddooollc::;;;;;;::::::::cllloodddxxkkkxxxxxxxxxxxxxxxxxkkkkkkOOOkkxxxdddddxxddxxxxxxxxxxxxxxxxxxxxdddddddddddddddddddddddddddddddddddddooooooooooooooooooo xxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxkOOxxxkOOOkxddooooddddxxxxkkkkkkkkkxxxxdolc:;,'''....',,,,;;;;;::ccllodxxxxxxxxxdoooooollllloddddooddxxxxddddddddxxxxxxxxxxxddddxxxxxxxxddddddddddddddddddddddddddddddddddddddoooooooooooooooooo xxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxkOOkxkOOOOkddoooodddddxxxkkkkkOOOkkkkkkxddxxdol:;,',:cc;,,,,,,;;:clodxxxxkxxdoolcc::;;;;;;::llllllloooodddddddddxxxxxxxxxxxxdddxxxxddxdddddddddddddddddddddddddddddddddddddddoooooooooooooooooo xxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxkkkkOkkOOOOkdooooooodddxxxkkkOOOOOOOOOOOOkkOO00Okxdddddolcc::::ccloooddxxkkxxol:;,,'''''''',,,;::ccllooddddddddddxxxxxxxxxxxxxxxxxxxddddddddddddddddddddddddddddddddddddddddddoooooooooooooooooo xxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxkOOOOOOOOOOkdooooooooddxxxkkkOOOOOOO00000OOOOOOOOkkxxddoolllllodxxxxxxkkOkkkxo:,'''..........'',,;:cloddxxdddoxxxxxxxxxxxxxxxxxxxxdddddddddddddddddddddddddddddddddddddddooooooooooooooooooooooo xxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxkO00OOOOOOOxdooooooooddxxxkkkOOOO000000000OOOkkkkxxdddoooloodxxkkkkkkkOOO0OOkdc,,'''',,,'''.',;:;;:clodxxxxxddxxxxxxxxxxxxxxxxxxxxxxxxxxddddddddddddddddddddddddddddddddoooooooooooooooooooooooo xxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxkOO00OOkOOOxdooooooodddxxxxkkOOOO00000000000OOkkxxxxxxxxxxkkOOOOOOOOkOOO0000Okdlc:;:cllooooooodddddddxxxxxxdddxkxxxxxxxxxxxxxxxxxxxxxxdddddddddddddddddddddddddddddddddddooooooooooooooooooooooo xxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxkkkkOO000OOOOkdooooooooddddxxkkkOOOO0000000000000OOOOOOOOOOOO000OOOOOkkkO0000000OkkxddddddxxkkkOOOOkkkOOOkkxxddxkkxxxxxxxxxxxxxxxxxxdxxxdddddddddddddddddddddddddddddddddddooooooooooooooooooooooo xxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxkOOOOOOOOxooooooooodddddxxkkkOOOO00000000000000000000000000OOOOOkkkkO000KK00000K0OkkxxxkkkkkkkkOOO00OOkkxddxkxxxxxxxxxxxxxxxxxdddxxxxdxxxddddddddddddddddddddddddddddddooooooooooooooooooooooo xxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxkkkOOOOkxdoooooooooooddddxxkkkOOO00000000000000000000000000OOOOkkkkkO000KK0000KKKKK0OOkkkkkkkOO00000OOkxxdxkxxxxxxxxxxxxxxxxxxddddddxxxxxxddddddddddddddddddddddddddddddoooooooooooooooooooooo xxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxkkkkkxxxdooooooooooooodddxxkkkOO0000000000000000000OOOOOOOOOOkkkkkO0K00KK0000KKKKKKKK0000KKKKK00000OOkxxxkkxxxxxxxxxxxxxxxxxxxxxddddxxxxxxxddddddddddddddddddddddddddddddddoooooooooooooooooo xxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxdooooooooooooooddxxxxkkOO0000000000000OOOOOOOkkkOOOOOOkkkkO0K00KK0O00KKKKKKKKKKKKKKKKKK000OOkkxxxkkxxxxxxxxxxxxxxxxxxxxxxxxdxxxxxxxxxxxdddddddddddddddddddddddoddddoooooooooooooooood xxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxdoooooooooooooooddxxxxkkOOOOOOOOOOOOOOOOkkkxxxxxxxkOOkkkkkO0K00KK0OOO000KKKKKKKKKKKKKKK00OOkkxxxxkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddxddddddxxdddddddddddddddooooooooooooooooooooooo xxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxkkxoooooooooooooooddddxxxxkkkkkkkkkkkkkkkxxddooddxxxkkkkkkkkO000KKK0OkkkkkOO00KKKKKKKKKK000Okkxxdxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddddxxxxddxddddddddddddddddddooooooooooooooooooooo xxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxkOOxdllooooddoooooooodddxxxxxxxxxxkxxxxxxddooooodxkOOOkkkkkkO00KKKKK0OkkkxddxkOO0000KKK000OOOkkxddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddxdddddddddddoooooooooooooooooooooooo xxxxxxxxxxxxxxxxxxxkkxxkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxOOOkxdllooooddddooooooodddddxxxxxxxxxxddddollodxxdxkOOOOkkkkkO0KKKKXKOOOOOxooddxkOOOOOOOOOOkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddddddddddddddddooooooooooooooooooo xxxxxxxxxxxxxxxxxxxxxxxkkkxxkkxkkkkxkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxOOOkkkdlllooodddddooooooooddddxxxxxxddddoollldxkOOkxxkkkkkkkkkO00KKKK0OOOOOxolloddxkkkkkkkkxxxxxxxxxxxxxxkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddddddddddddddddooooooooooooooooooo xxxxxxxxxxxxxxxxxxxxxxxkkxxxkkxxkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkOOxxOklclloooddddddoooooddddxxxddddddoollcloxkOO000OxddddxxxxkkOOOOOOOkkkkxoc:ccloddxxxxxddddxxxkxxxxxxkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddddddddddooooooooooooooooooo xxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkOOxxO0d;:clooooddddddooodddxxxxxddddoolllldxkOOOOO000Okxddooddxxxxxxxxxxxxxxoc;::cllodddddddddxxkkkkkOkkOOOOkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddxxxddxxdddddddddddooooooooooooooooooo xxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkxxkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkO0Oxx00o,;cllloodddddoooddddxxxxxxddoollodxkkkkkOOOOOOOOOOkxxdooooooooodddxxkxo:;::cloooddddddxxkkO0000000000000000OOOkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxdxxxddxddddddddddddooooooooooooooooooo xxxxxxxxxxxxxxxxxxkkkkkkkkkxxxxxxxxkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkOKK0dxKOc,;cllllooddddddoddddxxxxxxdddoodxkkkkkkkkOOOOOOOOkkkkkxdolccclodxxxkkkxdl::ccloodddddxxkkO0KKKKKKKKKKKKKKKKKKKKK00OOOkkkkkkxxxxxxxxxxxxxxxxxxxxxxxdddddddddddddddooooooooooooooooooo xxxxxxxxxxxxxxxxxxkkkkxxkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkO0KXKkxOOc,;lllllloooddddoddddxxxxxxxxddxxxxxxxxxkkkkOOOOkkkkkkkkxxdollloddxxxxxxxolcclodddxxxxxkkO0KKXXKKK0KKKKKKKKKKXXXXXXXXKK00OOkkxxxxxxxxxxxxxxxxxxxxxxdxxdddddddddddddoooooooooooooooooo xxxxxxxxxxxxxxxxxxxxxxxxxkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkO0KKXXKOkkc,:loollllloooddddddxxxxxxkxxxxxxxxdooooddxxkkkkkkkkkkkkxxxxxdoooddxxxxxolcccoddxxxxxxkkO0KKXXXXK00KKKKKXXXKKKKXXXXXXNNXXXK00Okkxxxxxxxxxxxxxxxxxxxdxxddddddddddddddooooooooooooooooo xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkxdxO0KKKXXNX0kl;:loooolllloooddddddxxxxxkkxxxxxxddddddddddddddddxxxxxxxxxxxxdddddddddddl:clodxkkkkkkkO0KKXNNNXK00KKKKXXXXKKKKKXXXXKKXNNNNNXXK0OOkkxxxxxxxxxxxxxxddddddddddddddddddddooooooooooooooo xxxxxxxxxxxxxxxxxxxkkxxxxxxxxxxxkxxxxxxxxxxxxxxxxxxkkkkkOOOOOxxO0KKKKXXXNNKkccloodoollllloooddddxxxxxxxxxxxxxddddxxxkkkxxxddooooolloodooooooddddxxkkdclodxkkkxxkkO0KKXXNNNXK0KKKXXXXXKK00KKXXXXKKKXNNWNNXXXXKKK0Okkkkxxxxxxxxxdddddddddddddddddddooooooooooooooo xxxxxxxxxxxxxxxxxkkkkxxxxxxxxxxxxxxxxxxxxxxxxkkkkkOO000000KKOxk00KKKKKXXXNNX0dooodddoollllooodddddxxxxxxxxxxxxxxxxxkkkkkkkkOkkkkkkxxddddxxkkkkkkkkkxdlloxkkxxxxkO0KKXXNNNNXKKKKXXXXXXK0000KKXXXKK0KXNNNNXKKXXXXXXK00Okkxxxxxxxdddddddddddddddddddooooooooooooooo xxxxxxxxxxxxxxxxxkkkkxxxxxxxxxxxxxxxxxxxxxkkkOO000KKKKKKXXXKOxOKKKKKKKXXXXXNNXOxddddddolllloooddddddxxxxxxxxkkkkkkkkkkkOkkkkkkkOOOOOOOOOOOkkkkkkkkkkxdodxkxxxxkO0KKXXXNNNXXKKKKXXXNXXKOOO00KKKXXK00KXNNNXK0KXXNNNNNXXK0Okkxxxxxxddddddddddddddddddoooooooooooooo xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkxxxxxkkOO00KKKKXXXXXXXNNNXOk0KKKKKKKKXXXXXNNNX0kxddddollllooodddddddddxxxkkkkkkkkkkkkkkkkkxxxddxxxxxxxxxxxxxkkkkkkkxdxxxxdxkO0KKXXXNNNXXKKKKXXXNNNX0OkOO00KKKKK0KXXXXXXK00KXNNNNNNNNXXK0Okxxxxxdddddddddddddddddoooooooooooooo xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkOO000KKKXXXXXNNNNNNNNNN0kOKKKKKKKKKXXXXXXNNNX0kxdddollloooodddddddddxxxkkkOOOOOOkkkkkkkkkxxddddddddddxxxkkkkkkkkxxxxddxkO00KKXXXNNXXXKKKKXXNNNXK0kkkOO00KKKKKKXNNXXXK00KXNNNNNNNNNNNXXK0Okxxddddddddddddddddddooooooooooooo xxxxxxxxxxxkkkkxxxxxxxxxxxxxxkkkOOO000KKKKXXXXNNNNNNNNNNNNNNKkOKXXXXKKKXXXXXXXXXNNNNK0kxdoolllooodddddddddxxxkkkkOOOOOkkkkkkkkxxxddddoooddxxkkkkkkkkkkxxddxkO00kOKXXXNNXXXXXXXXNNNNXK0kkkOOO000KKKKXNNXXXK00KXNNNNNNNNWWWWWNNXKOkxxddddddddddddddddddooooooooooo xxxxxxxxxxxkkkkxxxxxxxxxxxkkOOO00KKKKXXXXXXNNNNNNNNNNNNNNNNWN0kOXXXXXXXXXXXXXXXXXXXNNNXKOkxdooooodddddddddddxxxkkkkkkkkkkkkkkkkkkkxxxxxxxxxkkkkkkkkkkkxxxxk0000OkOKXXNNXXXXXXXNNNNNXKOkkkkkOO00000KXNNXXK000KXNNNNNWWWWWWMMWWNNXK0kxxxdddddddddddddddooooooooooo xxxxxxxxxxxkxxxxxxxxxxxxkOO00KKKXXXXXNNNNNNNNNNNNNNNNNNNWWNWNXOk0XXXXXXXXXXXXXXXXXXXXXNNNXK0kxdoooddddddddddxxxxxkkkkkkkOOOOOOOOOOO000000OOOOkkkkkkkkxxxkO000000OkOXNNNXXXXXXNNNNNNXK0kkkkkkOO000KXXNNXKK00KKXNNNWWWWWWMMMMMMWWWNNK0kxxddddddddddddddooooooooooo xxxxxxxxxxxxxxxxxxxxxkOO0KKKXXXXXNNNNNNNNWWNNNNNNNNNNWWWWWWWWNXOk0XNNXXXXXXXXXXXXXXXXXXXXNNNXX0OkdoodddooddddddxxxxxxkkkkkkOOOOOOOO0000000OOOkkkkkkkxxkO0KKKKKK00OkOXNNNXXXXNNNNNNNXK0OkkkkkkO000KKXNNXKKKKKXNNWWWWWMMMMMMMMMMMMWWNNK0kxxdddddddddddddoooooooooo xxxxxxxxxxxxxxxxxkkOO00KKXXXXNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWX0k0XNNNNXXXXXXNNNNXXXXXXXXXXXXNNXKOxddddddooddddxxxxxxxkkkkkkkOOOOOOOOOOOOOkkkkkkkxkO0KKKKXXXXXXKKOk0XNNNNNNNNNNNNNXXKOkkkkkOO000KKXNNXKKKKXXNWWWMMMMMMMMMMMMMMMMMWWNXKOkxxdddddddddddoooooooooo xxxxxxxxxxxxxxkkOO00KKXXXNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0OOXNNNNNNNNNNNNNNNNNNNXXXXXXXNNNNXOxdddddddodddddxxxxxxxxxxkkkkkkkkkkkkkkkxxkkkk0KXXXKKKXXXXNNNNXOkKNNNNNNNNNNNNNXXK0OkkkkOO000KKXNNXXKKKXNWWMMMMMMMMMMMMMMMMMMMMWWWNXKOkxddddddddddddoooooooo xxxxxxxxxxxkkO00KKKXXXNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKOOKNWNNNNNNNNNNNNNNNNNNNNNXXNNNNNNKOxdddooooodddddddddxdddxxxxxxxxxxxxxxxxkO0KXNNNXKKKKXXXNNNNNNKOOKNNNNNNNNNNNNNXXKOkkkkOO000KKXNNNXKXXWWMMMMMMMMMMMMMMMMMMMMMMMMWWWNXKOkddddddddddddooooooo xdxxxxxxkkO00KKKXXXNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWX0O0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXK0OkxxddooodxxxddddddddddddddddddddxkO0KXNNNNXKKKKKXXXNNNNNNNKkOXNNNNNNNNNNNNNXKOkkkkOOO00KKXNNNNXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNX0kxddddddooooooooooo xdxxxkkO000KKKXXXNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKO0XNNWWWWWWWWNNNNNNNNNNNNNNNNNNNNNXK00OOOkkxxxkkxxxxxxxxxxxxxxxxxxkO0KXXNNNNNXKKKKKXXXNNNNNNNNN0kKNWWNNNNNNNNNNXK0OkkOOOO00KKXNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNK0kdddddooooooooooo kdxxkO000KKKXXXNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXOOXWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNXXK0OOkkkkkkkkkOOOOO00000000OkOKXNNNNNNNNXKKKXXXXXNNNNNNNNNNXOOXNWWNNNNNNNNNXXK0OkOOO000KXNWWWMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNX0kxddddoooooooooo kxxkO00KKKXXNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXOOXWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNXXK0OOkkxkkkOOO00000KKK0OkddOXNNNNNNXXXKKXXXXXXNNNNNNNNNNNNKO0XWNNNNNNNNNNXXK0OOOO00KKXWWMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNXKOxdddddoooooooo OkOO0KKXXXNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKO0NWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNXXK0OOkkkkOOOOO0KKKKKKKKKKXNNXK000KKKKKKKXXXNNNNNNNNNNNNNNKO0NNNNNNNNNNXXXK00OO00KXNWMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNKOxddddddoooooo 0OO0KKXXXNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKOKNWWWWWMMWWWWWWWWWWWWWWWNNNNNNNNNNNNXXK00OOOOOOOOKXNNNNNNNNNNNNKkxdxxxxkO0KKXXNNNNNNNNNNNWWWN0OKNNNNNNNNNXXXKKKKKXXNWWMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNX0kddddddddooo 0O0KKXXXNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKOKWWWWWMMMWWWWWWWMMMWWWWWWWNNNNNNNNNNNXXXK00OOkkOXNXXXNNNNNNNNXOkxxxdddoddxk0KXNNNNNNNNNNWWNNXOOXNXXNNNNNNXXXNNNNWWWMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNX0kxddddddddd 000KKXXNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN00XWWWWMMMMWWWWMMMMMMMMMMMWWWNWWWWWWWWWNNNXK0Okx0XXKKXNNNXXXNXKK00OOkxxddooddk0XNNNNNNNNNWWWWNKO0XNNNNWWWWWWWWMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNKOxdddddddd K0KKXXNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWX00NWWMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMWWWWNK0O0XX00KXNXXXXXXXXXXKKOkxxdddddddkKNNNNNNNWWWWWNX0kKNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNKOxddddddd K0KXXNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXOKNWWWMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMWNNXXNNXK0KKKXXXXXXXXXXXKOkxxdddddddk0XNNNNWWWWWWWWXOONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNNKOxdddddd KKKXXNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKOKNWWWMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMWWNNNNNNNXXXXKKKKXXXXXKKK0Okxddddddddx0XNWWWWWWWWWWNKOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNXKOxddddd KKXXNNNWWWWWWMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWNK0XWWWMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMWWWNNWWNNNNXXKKKKKKKKKKKKOkkxddddddddxKNWWWMMMMMMMWN00NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWNNKkxdddd XKXXNNWWWWWWMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMWWWWWWWWWWWWWN00XWWWMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMWWWWWWWWWWNXXXKKKKKKKKKOkkxdddddddddONWWMMMMMMMMMWK0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMWWWWWWWWWNNKOxddd XXXXNNWWWWWMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMWWWWWWWWWWWMMMMMMMMWWWWWWWWWX00NWWWWMMMMMMMMMMMMMMMMWNWWMMMMMMMMMMMMMMMMMWWWMMMMMWWWNNNNXXXXXK0Okkxdddddxxk0XWWMMMMMMMMMWK00XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWMMMMMMMMMWWWWMMMMMMMMMMMMMMMMMWWWWWWWWWWNNKOxdd XXXNNNWWWWWMMMMMMMMWWWWWWWWWWWWWWWWWWWMWWWWWWWWMMMMWWWWWWWWWWWMMMMMMMMMWWWWWWWWWX0KNWWWMMMMMMMMMMMMMMMMWNNWMMMMMMMMMMMMMMMMMMWWMMMMMMMMMWWWWWNNNXXK0OOkkkOO00KXXWWMMMMMMMMMWX0OKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWWMMMMMMMWWWWWMMMMMMMMMMMMMMMMMWWWWWWWWWWWNNKOxx XXXNNNWWWWWMMMMMMMMMWWWWWWWWWWWWWWMMMMMMMMWWMMMMMMMWWWWWWWWWWMMMMMMMMMMMMWWWWWWWNKOKWWWWWMMMMMMMMMMMMMMWNXWWMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMWWWWWNNNNXXXXNNNXXNWMMMMMMMMMWXX00XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMMWWWWWWWMMMMMMMMMMMMMMMWWWWWWWWWWWWNNKOk XXXNNNWWWWWWWMMMMMMMMMWWWWWWWWWMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWMMMMMMMMMMMMWWWWWWWWN0OXWWWWMMMMMMMMMMMMMMWNXNWWWMMMMMMMMMMMMMMMWWWWMMMMMWWWWWWMMMMMMMMMMMMWWWNNXXXNWWMMMMMMMMWNNX0KNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWMMMMMMWWWWWWWMMMMMMMMMMMMMMMWWWWWWWWWWWWWNNXO XXXXNNWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWMMMMMMMMMMMMMMWWWWWWWX0OXWWWWMMMMMMMMMMMMMWNXNWMMMMMMMMMMMMMMMMMWWWWWMMMWNWWWWWWNWWWMMMMMMMMWWNNXXXNWWMMMMMMMMWNNNKOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMWWWWWWWMMMMMMMMMMMMMMMMWWWWWWWWWWWWWNNK XXXXNNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWMMMMMMMMMMMMMMMWWWWWWWX0OXWWWMMMMMMMMMMMMMWXXNWMMMMMMMMMMMMMMMMWWNNNWMMWWNNNWWWNNWWMMMMMMMMMMWWNXXXNWWMMMMMMMMWNNWX00NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMWWWWWWWMMMMMMMMMMMMMMMMMWWWWWWWWWWWWNNN XXXXNNWWWWWMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWMMMMMMMMMMMMMMMMWWWWWWWXO0NWWWWWMMMMMMMMMMWXXWMMMMMMMMMMMMMMMMMMWWNNNWMMWWNNNWWWMMMMMMMMMMMMMMWWNXXNWWMMMMMMMMMWNWWX0KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWMMMMWWWWWWWMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWNN XXXXXNNWWWWMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWMMMMMMMMMMMMMMMMMWWWWWWWKO0NWWWWWMMMMMMMMMWNNMMMMMMMMMMMMMMMMMMMWWNNNWMMMMWWWWMMMMMMMMMMMMMMMMMWNXNNWMMMMMMMMMMWNNWN00NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNWMMMMWWWWWWWMMMMMMMMMMMMMMMMMMMMWWMWWWWWWWWW XXXXXNNWWWWWMMWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWMMMMMMMMMMMMMMMMMMMWWWWWNKOKNWWWWWWMMMMMMWWWWMMMMMMMMMMMMMMMMMMMMWWNNNWMMMMMMMMMMMMMMMMMMMWWMMMWWNNWWMMMMMMMMMMMWNWWKOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWWMWWWNWWWWMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWW XXXXXNNWWWWWWMWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWMMMMMMMMMMMMMMMMMMWWWWWWNKOKNWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMWWNNWMMMMMMMMMMMMMMMMMMMMMMMMWWNNWWMMMMMMMMMMMWNNWNK0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNWWWWNNWWWWMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWW XXXXXNNWWWWWMMMMWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWMMMMMMMMMMMMMMMMMWWWWWWX0OXWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMWWWNWWMMMMMMMMMMMMMMMMMMMMMMMMWWWWWMMMMMMMMMMMWWNNNX0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNWWWWNWWWWWMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWW"


@app.post("/tasks")
async def create_task(session: SessionDep,title: str, description: str="brak opisu",status: str = "do wykonania"):
    TaskTools.task_crate_validator(title, description, status)
    task_id = str(uuid4())

    db_task = Task(
        id=str(task_id),
        title=title,
        description=description,
        status=status
    )

    session.add(db_task)
    session.commit()
    session.refresh(db_task)

    return f"updated with task: {db_task}"
@app.get("/tasks")
async def get_tasks(session: SessionDep,status:str | None=None):

    if status == None:
        return session.exec(select(Task)).all()
    else:
        TaskTools.status_validator(status)
        return session.exec(select(Task).where(Task.status == status)).all()

@app.get("/tasks/{task_id}")
async def get_task_details(session: SessionDep,task_id:str):

    TaskTools.task_by_id_validator(task_id)

    return session.get(Task, task_id)

@app.put("/tasks/{task_id}")
async def update_task(session: SessionDep,task_id: str, title: str, description: str, status: str):
    TaskTools.task_by_id_validator(task_id)
    TaskTools.task_crate_validator(title,description,status)

    task = session.get(Task, task_id)
    task.title = title
    task.description = description
    task.status = status

    session.commit()
    session.refresh(task)

    return task

@app.delete("/tasks/{task_id}")
async def delete_task(session: SessionDep,task_id: str):
    TaskTools.task_by_id_validator(task_id)


    task = session.get(Task, task_id)
    session.delete(task)
    session.commit()

    return "deleted " + str(task)

@app.post("/pomodoro")
async def create_pomodoro_timer(session: SessionDep,task_id:str):
    TaskTools.task_by_id_validator(task_id)
    PomodoroTools.pomodoro_create_validator(task_id)
    start_time = datetime.now()
    end_time = start_time + timedelta(minutes=25)
    completed = False

    task = session.get(Task, task_id)


    new_pomodoro = PomodoroSession(
        id=str(task_id),
        start_time=start_time,
        end_time=start_time + timedelta(minutes=25),
        completed=False
    )

    session.add(new_pomodoro)
    session.commit()
    session.refresh(new_pomodoro)

    return f"Pomodoro created: {new_pomodoro}"

@app.post("/pomodoro/{task_id}/stop")
async def stop_pomodoro(session: SessionDep,task_id: str):
    TaskTools.task_by_id_validator(task_id)
    PomodoroTools.pomodoro_stopper_validator(task_id)
    for pomodoro in pomodoro_list:
        if str(pomodoro.id) == str(task_id):
            pomodoro["completed"] = True
            pomodoro["end_time"] = datetime.now()

    pomodoro = session.get(PomodoroSession, task_id)
    pomodoro.completed = True
    pomodoro.end_time = datetime.now()

    session.commit()
    session.refresh(pomodoro)



    return f"Pomodoro stopped: {pomodoro}"

@app.get("/pomodoro/stats")
async def get_pomodoro_stats(session: SessionDep):


    completed_sessions = session.exec(select(PomodoroSession).where(PomodoroSession.completed == True)).all()

    total_time = sum((session.end_time - session.start_time for session in completed_sessions),timedelta())

    stats = []
    tasks = session.exec(select(Task)).all()

    for task in tasks:
        for task in tasks:
            task_sessions = session.exec(
                select(PomodoroSession)
                .where(PomodoroSession.id == task.id)
                .where(PomodoroSession.completed == True)
            ).all()

        stats.append({
            "id": task.id,
            "completed_sessions_for_task":len(task_sessions),
            "total_time_for_task": sum((session.end_time - session.start_time for session in task_sessions),timedelta())

        })

    return f"total time = {total_time}, completed sessions = {len(completed_sessions)},stats = {stats}"











